// WARNING: DO NOT DELETE THIS FILE
// This file was auto-generated by the Witnet compiler, any manual changes will be overwritten.
const WitnetRequestBoardProxy = artifacts.require("WitnetRequestBoardProxy")
const WitnetRequestBoard = artifacts.require("WitnetRequestBoard")
const CBOR = artifacts.require("CBOR")
const Witnet = artifacts.require("Witnet")

const addresses = {
  "goerli": {
    "CBOR": "0x8e3b1DD86560c99070C4852242235Cb7065277Fe",
    "Witnet": "0x06B871C3a9FDd68a6e1Db1F4050C645A3229f929",
    "WitnetRequestBoardProxy": "0xF1788C0e04322d54a07f6c8E8f933185D4cddca7",
  },
  "rinkeby": {
    "CBOR": "0x5E5E204dB746f97E1bBBFAf3639E760177eDbFf9",
    "Witnet": "0x14a2C568AF4F3fa834C907cC08E2C6c5019daaC1",
    "WitnetRequestBoardProxy": "0x3F993030e2ba6473B5AaC2DaEA4A64b05500Ac8B",
  },
}

module.exports = function (deployer, network, accounts) {
  network = network.split("-")[0]
  if (network in addresses) {
    Witnet.address = addresses[network]["Witnet"]
    WitnetRequestBoardProxy.address = addresses[network]["WitnetRequestBoardProxy"]
  } else {
    deployer.deploy(CBOR)
    deployer.link(CBOR, Witnet)
    deployer.deploy(Witnet)
    deployer.deploy(WitnetRequestBoard, [accounts[0]]).then(function() {
      return deployer.deploy(WitnetRequestBoardProxy, WitnetRequestBoard.address)
    })

  }
}
