// This file was auto-generated by the Witnet compiler, any manual changes will be overwritten except
// each contracts' constructor arguments (you can freely edit those and the compiler will respect them).
const Witnet = artifacts.require("Witnet")
const WitnetRequestBoard = artifacts.require("WitnetRequestBoardInterface")
const BtcUsdPriceFeed = artifacts.require("BtcUsdPriceFeed")
const EthUsdPriceFeed = artifacts.require("EthUsdPriceFeed")
const GoldEurPriceFeed = artifacts.require("GoldEurPriceFeed")

module.exports = async function (deployer) {
  await deployer.link(Witnet, [BtcUsdPriceFeed, EthUsdPriceFeed, GoldEurPriceFeed])

  await deployer.deploy(BtcUsdPriceFeed, WitnetRequestBoard.address)

  await deployer.deploy(EthUsdPriceFeed, WitnetRequestBoard.address)

  await deployer.deploy(GoldEurPriceFeed, WitnetRequestBoard.address)
}
