// This file was auto-generated by the Witnet compiler, any manual changes will be overwritten except
// each contracts' constructor arguments (you can freely edit those and the compiler will respect them).
const Witnet = artifacts.require("Witnet")
const WitnetRequestBoardProxy = artifacts.require("WitnetRequestBoardProxy")
const BtcUsdPriceFeed = artifacts.require("BtcUsdPriceFeed")
const EthUsdPriceFeed = artifacts.require("EthUsdPriceFeed")
const GoldEurPriceFeed = artifacts.require("GoldEurPriceFeed")

module.exports = async function (deployer) {
  await deployer.link(Witnet, [BtcUsdPriceFeed, EthUsdPriceFeed, GoldEurPriceFeed])
  await deployer.deploy(BtcUsdPriceFeed, WitnetRequestBoardProxy.address)
  await deployer.deploy(EthUsdPriceFeed, WitnetRequestBoardProxy.address)
  await deployer.deploy(GoldEurPriceFeed, WitnetRequestBoardProxy.address)
}
