const queries = require("../migrations/witnet-queries")
const examples = Object.keys(queries)
console.log("Available Witnet price feeds ready for deployment:\n")
examples.forEach(example => console.log(`  ${example}`))
console.log()
