const requests = require("../migrations/witnet.requests")
const examples = Object.keys(requests)
console.log("Available Witnet price feeds ready for deployment:\n")
examples.forEach(example => console.log(`  ${example}`))
console.log()
